site_name: Probextreme
site_url: https://github.com/ArcticSnow/probextreme
site_author: Simon Filhol, François Doussot
copyright: GNUv3 License
nav:
  - Home: index.md
  - Probextreme: probextreme.md
  - API:
      - Frequentist: api/probextreme.frequentist_extreme.md
      - Bayesian: api/probextreme.bayesian_extreme.md
      - Statiscal test: api/probextreme.stat_test.md
      - Utils: api/probextreme.utils.md
theme:
  name: material
  palette:
    primary: teal
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
